version: '3'
services:
  transmission-telegram:
    container_name: transmission-telegram
    hostname: transmission-telegram
    build: .
    environment:
      - BOT_TOKEN=123456789:MyToken
      - MASTERS=@myuser
      - TRANSMISSION_URL=http://transmission:9091/transmission/rpc
      - TRANSMISSION_USERNAME=myuser
      - TRANSMISSION_PASSWORD=mypass
      - TZ=Europe/Moscow
