on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - run: make check
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          make docker
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && \
          docker push docker.pkg.github.com/zhulik/transmission-telegram/transmission-telegram:latest
